### PR TITLE
Fix actor mtx interpolation flag persisting through skipped frames

### LINKED ISSUE #899: Model flicker on camera cuts with interpolation enabled
- [x] I have checked the known issues and searched Github to ensure this issue has not already been reported.
- [x] This is not a feature request, I know those belong on Discord/Github Discussions.

### Description of the bug:
On the most recent update, after any camera cut in a cutscene, the character models will flicker for a frame when interpolation is enabled

### Can you reproduce? If so please list the steps:
- [ ] No, I cannot reproduce this bug
- [x] Yes, here are the steps to reproduce the bug:
1. Start any cutscene
2. Enable interpolation and wait for camera cut
3. See the flicker

### Screenshots or videos:

https://github.com/user-attachments/assets/038049d2-ff98-4d88-852d-73329991878b

### System Information:
- OS: Linux
- GFX Backend: OpenGL
- Game Version: 1.1.2
- Rom Version: US 1.0

### PR DESCRIPTION
**Pull request by Archez**
The `FrameInterpolation_IgnoreActorMtx` was missing a check for if the current frame was being recorded for interpolation or not, this meant the logic in RecordCloseChild was not executed and prevented the `ignore_inv_actor_mtx` from being cleared. It would then apply to every actor on the next recorded frame until the first `FrameInterpolation_IgnoreActorMtx` is encountered (usually links feet shadow).

Added flag clearing at the state of a frame as a backup to ensure nothing lingers from a previous frame.

Fixes #899 

### Build Artifacts
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2356823118.zip)
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2356823533.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2356837379.zip)

### CODE REVIEW

**Review by garrettjoecox — APPROVED** [review]

**Comment by Humor0u5** [comment]
i ca no longer download this fix

**Comment by Malkierian** [comment]
You don't have to, it's been merged into the codebase. Just use a nightly playtest build.

**Comment by swordwaterdrinker** [comment]
Does anyone know how to get this fixed on Android? I still have this issue with the most recent version and I'm not sure there are nightly playtest builds of the android version.

**Comment by OtherBlue** [comment]
> Does anyone know how to get this fixed on Android? I still have this issue with the most recent version and I'm not sure there are nightly playtest builds of the android version.

You wait for the next update on android to come out

**Comment by swordwaterdrinker** [comment]
> > Does anyone know how to get this fixed on Android? I still have this issue with the most recent version and I'm not sure there are nightly playtest builds of the android version.
> 
> You wait for the next update on android to come out

I guess I was hoping someone would have/know a way to fix this in the same way that it was fixed for the other platforms that a complete layman could implement

**Comment by garrettjoecox** [comment]
> I guess I was hoping someone would have/know a way to fix this in the same way that it was fixed for the other platforms that a complete layman could implement

It’s not that the fix is incompatible with android, it’s that the android build is behind, and needs to be updated to get the fix.

**Comment by NoseDevilEugen** [comment]
i should note here that current Portmaster build (for cheap handhelds like anbernic) suffers from exactly same issue (weird frames between camera jumps when interpolation is active)
Said to be built from the develop branch (bleeding edge) on 03/10/2025

if someone has solution for it, kick me please.

**Comment by JeodC** [comment]
> i should note here that current Portmaster build (for cheap handhelds like anbernic) suffers from exactly same issue (weird frames between camera jumps when interpolation is active) Said to be built from the develop branch (bleeding edge) on 03/10/2025
> 
> if someone has solution for it, kick me please.

https://github.com/JeodC/RHH-Ports

I maintain it here. All HM64 ports are based on release tags now.

**Pull request merged**
