### PR TITLE
Add alt assets toggle to menus

### PR DESCRIPTION
**Pull request by Archez**
Adds the alt assets toggle to the menus (_finally!_). I stuck it in graphics > mods to align with SoH.

image

### Build Artifacts
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2160407418.zip)
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2160409747.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/2160423202.zip)

### CODE REVIEW

**Comment by garrettjoecox** [comment]
Thoughts on adding a checkbox for the `tab` hotkey? I absolutely despise it

**Comment by Archez** [comment]
As in a toggle to enable/disable the tab hoykey? It would have to default on. Where would you like to see that, maybe in the Settings area where the side bar search toggle is?

**Comment by garrettjoecox** [comment]
> As in a toggle to enable/disable the tab hoykey? It would have to default on. Where would you like to see that, maybe in the Settings area where the side bar search toggle is?

Could just be right underneath/above this one but no strong opinion. But yeah, I've resorted to just keeping it commented out locally, frequent user of alt-tab.

**Comment by Archez** [comment]
I'll just stick it in settings, since that ideally will just get replaced when a proper hotkey system is made. Don't want the graphics menu feeling cramped (and search bar will expose it).

**Comment by Archez** [comment]
Alright, there we go 🚀

**Review by garrettjoecox — APPROVED** [review]

**Pull request merged**
