### PR TITLE
[Enhancement] Custom Zora Egg Count

### PR DESCRIPTION
**Pull request by Mothstery**
Allows users to set the required zora egg count for unlocking new wave bossa nova from any value in the 1 to 7 range. 

- Not sure if this should be in the "songs" category, even though it does technically relate to unlocking a song. Would like some input from a senior dev on that.
- Numeric variable instead of toggle. In case some players only want to do the pirates fortress for example, or however many bottles they have in their run at the time.

### Build Artifacts
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1839862572.zip)
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1839862720.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1839865114.zip)

### CODE REVIEW

**Comment by Mothstery** [comment]
Turns out this introduces a new dialogue bug with the marine researcher if your egg count is anything but 7. Going to work on addressing that, if I need to close this PR until then let me know.

**Comment by garrettjoecox** [comment]
> Turns out this introduces a new dialogue bug with the marine researcher if your egg count is anything but 7. Going to work on addressing that, if I need to close this PR until then let me know.

You are fine to leave it open! Feel free to reach out in #2s2h-development in discord for any questions/pointers!

**Comment by Mothstery** [comment]
This has been cleaned up to use hooks now, and played fine in the general testing I did. Ran it by the #2s2h-development channel last night, no complaints so far.

**Review by Archez — COMMENTED** [review]
The changes look good. Only thing is you've created a second `BeginMenu("Song/Playback")` instead of adding to the existing one. Please combine them and deal with merge conflicts (preferably we would like the items in alphabetical order after merging).

Placing in songs/playback I think is fine for now. It can always move in the future if the menu options evolve.

If you aren't available to deal with the merge conflicts, let me know and I can push it on your behalf.

**Comment by Mothstery** [comment]
> The changes look good. Only thing is you've created a second `BeginMenu("Song/Playback")` instead of adding to the existing one. Please combine them and deal with merge conflicts (preferably we would like the items in alphabetical order after merging).
> 
> Placing in songs/playback I think is fine for now. It can always move in the future if the menu options evolve.
> 
> If you aren't available to deal with the merge conflicts, let me know and I can push it on your behalf.

Thanks. This should be good now, UIWidget issue was fixed and I resolved the merge conflicts. Did a couple quick tests with different egg counts and they went as expected.

**Review by Archez — APPROVED** [review]
Great!

**Pull request merged**
