### PR TITLE
Hookshot cheats

### PR DESCRIPTION
**Pull request by cplaster**
Adds 'Hookshot Anywhere' and 'Hookshot Reach Multiplier' cheats.

This code is pretty much a straight copy from the same functionality in SoH. Seems to do the business just fine.

Its my first PR, be gentle :-D

### Build Artifacts
  - [2ship-mac.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1595945497.zip)
  - [2ship-linux.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1595949007.zip)
  - [2ship-windows.zip](https://nightly.link/HarbourMasters/2ship2harkinian/actions/artifacts/1595957009.zip)

### CODE REVIEW

**Comment by Malkierian** [comment]
Well, it's hard to be gentle in saying to try putting this into GameInteractor hooks instead of directly changing the source code XD

**Comment by cplaster** [comment]
Haha, thats plenty gentle, I appreciate the feedback :-)

I'm not familiar with the GameInteractor hook mechanism, is there simple example I should be looking at for reference?

**Comment by Malkierian** [comment]
Yeah, virtually any of the current enhancements.

**Comment by Malkierian** [comment]
That's not to say it will actually be possible, but a lot of the stuff you'd need access to should be accessible in one of the hooks, and the idea is to keep enhancements out of the MM source as much as possible.

**Comment by cplaster** [comment]
Gotcha, I'll have a look, thanks! I'll close this PR and resubmit once I get that sorted.

**Comment by Malkierian** [comment]
No need to close it. As you push new commits to your personal fork, the PR will automatically update.

**Pull request closed without merging**
